### ISSUE TITLE
A way to designate an instance as "main"

### ISSUE THREAD

**Issue by jasonswett** [jasonswett/exosuit#11]
I think by default commands like `exo ssh` should log into the "default" app and only by doing something like `exo ssh --choose` should you be able to choose from a list.

To make this possible, one app/instance will have to be able to be designated as "main".

**Comment by peterdenham** [comment]
Have you any thoughts on where this and possibly other settings/configs would be stored?

**Comment by jasonswett** [comment]
Yes, this is actually partway done at this point. There's a config file at `.exosuit/config.yml` which is managed by [this class](https://github.com/jasonswett/exosuit/blob/master/lib/exosuit/configuration.rb). You can see an example [here](https://github.com/jasonswett/exosuit/blob/master/lib/exosuit.rb#L35) where the `primary_instance_id` directive gets set on `.exosuit/config.yml`.

In case it helps to see, this is what my current config file happens to look like:

```yaml
---
aws_profile_name: personal
app_name: intolerable-awful-river
key_pair:
  name: intolerable-awful-river
  path: "/Users/jasonswett/.ssh/intolerable-awful-river"
primary_instance_id: i-0ce3091abd4413e2c
```

Now, when I run `exo ssh`, it sees my `primary_instance_id` and SSH's into that instance rather than prompting me like it used to.

So, unless you can think of any reason why not, I think this issue could actually be closed.

BTW this project totally needs a documentation site...it's on the long list of to-dos. :)
